-- AHLTV Open Tour schema
create table if not exists public.team_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  team_name text not null check (char_length(team_name) between 2 and 40),
  team_tag text not null check (char_length(team_tag) between 2 and 8),
  captain_nick text not null check (char_length(captain_nick) between 2 and 32),
  captain_email text not null check (char_length(captain_email) <= 254),
  contact text not null check (char_length(contact) between 2 and 80),
  captain_profile text, -- legacy field kept for compatibility
  team_logo_url text not null,
  players text[] not null check (cardinality(players) = 5),
  substitute text,
  note text check (char_length(note) <= 500),
  status text not null default 'pending' check (status in ('pending','approved','rejected'))
);

drop index if exists public.team_registrations_name_ci;
drop index if exists public.team_registrations_tag_ci;
drop index if exists public.team_registrations_tournament_name_ci;
create unique index team_registrations_tournament_name_ci
on public.team_registrations (tournament_id, lower(team_name))
where status <> 'rejected';

drop index if exists public.team_registrations_tournament_tag_ci;
create unique index team_registrations_tournament_tag_ci
on public.team_registrations (tournament_id, lower(team_tag))
where status <> 'rejected';

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.team_registrations enable row level security;
alter table public.admin_users enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.team_registrations to anon, authenticated;
grant select, update, delete on public.team_registrations to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.team_registrations_id_seq to anon, authenticated;

drop policy if exists "public can submit tournament registration" on public.team_registrations;

drop policy if exists "Users can read own tournament registrations" on public.team_registrations;
create policy "Users can read own tournament registrations"
on public.team_registrations
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "admin can read registrations" on public.team_registrations;
create policy "admin can read registrations"
on public.team_registrations
for select
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can update registrations" on public.team_registrations;
create policy "admin can update registrations"
on public.team_registrations
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can delete registrations" on public.team_registrations;
create policy "admin can delete registrations"
on public.team_registrations
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can read own admin membership" on public.admin_users;
create policy "admin can read own admin membership"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));


-- Auto-close registration when approved team limit is reached
create or replace function public.enforce_tournament_team_limit()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_max_teams integer;
  v_approved_count integer;
begin
  if new.status <> 'approved' then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and old.status = 'approved'
     and old.tournament_id = new.tournament_id then
    return new;
  end if;

  select t.max_teams
    into v_max_teams
  from public.tournaments t
  where t.id = new.tournament_id
  for update;

  if v_max_teams is null then
    raise exception using errcode = 'P0001', message = 'tournament_not_found';
  end if;

  select count(*)::integer
    into v_approved_count
  from public.team_registrations r
  where r.tournament_id = new.tournament_id
    and r.status = 'approved';

  if v_approved_count >= v_max_teams then
    raise exception using errcode = 'P0001', message = 'tournament_team_limit_reached';
  end if;

  if v_approved_count + 1 >= v_max_teams then
    update public.tournaments
    set registration_open = false
    where id = new.tournament_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_tournament_team_limit
on public.team_registrations;

create trigger trg_enforce_tournament_team_limit
before insert or update of status, tournament_id
on public.team_registrations
for each row
execute function public.enforce_tournament_team_limit();


-- Prevent duplicate Steam players inside one tournament
create or replace function public.enforce_registration_duplicates()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_new_links text[];
  v_total integer;
  v_distinct integer;
begin
  if new.status = 'rejected' then return new; end if;

  select coalesce(array_agg(normalized), '{}'::text[])
  into v_new_links
  from (
    select regexp_replace(lower(rtrim(btrim(link), '/')), '^https://www\.', 'https://') as normalized
    from unnest(coalesce(new.player_steam_links, '{}'::text[]) || coalesce(new.substitute_steam_links, '{}'::text[])) as u(link)
    where btrim(link) <> ''
  ) normalized_links;

  v_total := cardinality(v_new_links);
  select count(distinct link)::integer into v_distinct from unnest(v_new_links) as u(link);

  if v_total <> v_distinct then
    raise exception using errcode = 'P0001', message = 'duplicate_player_in_roster';
  end if;

  if exists (
    select 1
    from public.team_registrations r
    cross join lateral unnest(coalesce(r.player_steam_links, '{}'::text[]) || coalesce(r.substitute_steam_links, '{}'::text[])) as existing(link)
    where r.tournament_id = new.tournament_id
      and r.id <> coalesce(new.id, -1)
      and r.status <> 'rejected'
      and regexp_replace(lower(rtrim(btrim(existing.link), '/')), '^https://www\.', 'https://') = any(v_new_links)
  ) then
    raise exception using errcode = 'P0001', message = 'duplicate_player_in_tournament';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_registration_duplicates on public.team_registrations;
create trigger trg_enforce_registration_duplicates
before insert or update of tournament_id, status, player_steam_links, substitute_steam_links
on public.team_registrations
for each row execute function public.enforce_registration_duplicates();


-- Second bracket image for a tournament
alter table public.tournaments
  add column if not exists bracket_image_url_2 text;
