-- AHLTV Open Tour schema
create table if not exists public.team_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  team_name text not null check (char_length(team_name) between 2 and 40),
  team_tag text not null check (char_length(team_tag) between 2 and 8),
  captain_nick text not null check (char_length(captain_nick) between 2 and 32),
  captain_email text not null check (char_length(captain_email) <= 254),
  contact text not null check (char_length(contact) between 2 and 80),
  captain_profile text,
  players text[] not null check (cardinality(players) = 5),
  substitute text,
  note text check (char_length(note) <= 500),
  status text not null default 'pending' check (status in ('pending','approved','rejected'))
);

create unique index if not exists team_registrations_name_ci
on public.team_registrations (lower(team_name));

create unique index if not exists team_registrations_tag_ci
on public.team_registrations (lower(team_tag));

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.team_registrations enable row level security;
alter table public.admin_users enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.team_registrations to anon, authenticated;
grant select, update, delete on public.team_registrations to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.team_registrations_id_seq to anon, authenticated;

drop policy if exists "public can submit tournament registration" on public.team_registrations;
create policy "public can submit tournament registration"
on public.team_registrations
for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "admin can read registrations" on public.team_registrations;
create policy "admin can read registrations"
on public.team_registrations
for select
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can update registrations" on public.team_registrations;
create policy "admin can update registrations"
on public.team_registrations
for update
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can delete registrations" on public.team_registrations;
create policy "admin can delete registrations"
on public.team_registrations
for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "admin can read own admin membership" on public.admin_users;
create policy "admin can read own admin membership"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));
